### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by KunMinX** [techmovie/hexo-theme-instapaper#11]
git clone git@github.com:techmovie/hexo-theme-instapaper.git themes/instapaper --depth=1

正克隆到 'themes/instapaper'...
git@github.com: Permission denied (publickey).
致命错误：无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。

-

建议是通过 https 方式拉取

git clone https://github.com/techmovie/hexo-theme-instapaper.git themes/instapaper --depth=1

**Comment by xheiop** [comment]
没明白你想问什么，改成https方式拉取也不可以么

**Comment by KunMinX** [comment]
上方是 readme ssh 方式操作，以及终端报的信息，下方是本人建议的方式

**Comment by xheiop** [comment]
感谢建议 我改一下
