### ISSUE TITLE
Windows系统显示横向滚动条

### ISSUE THREAD

**Issue by liaocp666** [techmovie/hexo-theme-instapaper#2]
![image](https://user-images.githubusercontent.com/27202776/181001734-7ad298d0-2198-4cab-9af2-888d769b4558.png)

如上图所示，Windows系统会显示横向滚动条。

我找了下原因：[header.scss](https://github.com/techmovie/hexo-theme-instapaper/blob/525d05f1539178cbebd5c61255a771da6c9d3c1d/src/style/partial/header.scss#L6)  代码中的  `width: 100vw`  计算了滚动条在内的宽度。 

可以使用下面其中一种方式解决：

1. width: calc(100vw - (100vw - 100%));
2. width: 100%;

**Comment by liaocp666** [comment]
@techmovie hi，您怎么看待这个问题呢？如果是一个bug的话，我可以修复一下😉

**Comment by xheiop** [comment]
> @techmovie hi，您怎么看待这个问题呢？如果是一个bug的话，我可以修复一下😉

你直接改了提个PR吧
