### ISSUE TITLE
设置好之后页面打不开了

### ISSUE THREAD

**Issue by ghost** [techmovie/hexo-theme-instapaper#4]
页面显示：

doctype html(lang=config.language) include ./partial/header-base.pug body include ./partial/header.pug main section.main-content !{ body } include ./partial/footer.pug script(src=url_for('scripts/dark.js')) if is_post() script(src=url_for('scripts/post.js'))

**Comment by xheiop** [comment]
你的博客根目录有没有安装这个npm包： **hexo-render-pug**

**Comment by ghost** [comment]
谢谢~&nbsp;


sky
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rick ***@***.***&gt;; 
发送时间: 2022年9月28日(星期三) 下午2:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [techmovie/hexo-theme-instapaper] 设置好之后页面打不开了 (Issue #4)





 
你的博客根目录有没有安装这个npm包： hexo-render-pug
