### ISSUE TITLE
hexo g报错

### ISSUE THREAD

**Issue by wloverine** [techmovie/hexo-theme-instapaper#6]
在使用hexo g生成文章的时候报错了，错误信息如下：
ERROR TypeError: /Users/daryl/code/workspace/wloverine.github.io/themes/instapaper/layout/post.pug:7
    5|       span #{ time(page.date, 'YYYY-MM-DD HH:mm:ss') }
    6|       span.tags
  > 7|         each tag in page.tags.data
    8|           a(href=url_for(tag.path)) ##{ tag.name }
    9|   if page.featured_image
    10|     .feature-img

Cannot read property 'data' of undefined

请问这是什么原因，要怎么解决呢。

虽然最后还是能正常deploy，但还是希望解决下，谢谢!

**Comment by xheiop** [comment]
原因是有文章没有设置tag 已修复
